//===----------------------------------------------------------------------===//
//
// Copyright 2021-2022 The HCL-MLIR Authors.
//
//===----------------------------------------------------------------------===//

#ifndef BINDINGS_PYTHON_HCL_OPS_TD
#define BINDINGS_PYTHON_HCL_OPS_TD

include "mlir/Bindings/Python/Attributes.td"
include "hcl/Dialect/HeteroCLOps.td"

#endif // BINDINGS_PYTHON_HCL_OPS_TD